# Generated by Django 4.0.4 on 2022-05-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_sing', models.TextField()),
                ('gen_sing', models.TextField()),
                ('gender', models.CharField(choices=[('M.', 'Masculine'), ('F.', 'Feminine'), ('N.', 'Neuter')], default='M.', max_length=2)),
                ('declension', models.CharField(choices=[('1st', 'First'), ('2nd', 'Second'), ('3rd', 'Third'), ('4th', 'Fourth'), ('5th', 'Fifth')], default='1st', max_length=3)),
                ('definition', models.TextField()),
                ('chapter', models.IntegerField(default=1)),
            ],
        ),
    ]
